stages:
  - testes
  - relatorio

variables:
  NODE_ENV: "test"

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

testes_android:
  stage: testes

  tags:
    - android
    - appium

  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

  before_script:
    - node --version
    - npm --version
    - java -version
    - adb devices
    - npm ci --cache .npm --prefer-offline

  script:
    - npm run test:android

  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - reports/allure-results/
      - logs/

relatorio_allure:
  stage: relatorio

  tags:
    - android
    - appium

  needs:
    - job: testes_android
      artifacts: true

  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

  script:
    - npm ci --cache .npm --prefer-offline
    - npm run allure:generate

  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - reports/allure-report/